feat: PlaybackConfigs
Netsocs-Team/driver.sdk_go pull request #20
Opened 2024-07-12 19:06 UTC by cuervodelviento

Configs necesarias para conocer la url de playback así como los rangos de tiempo en que existen grabaciones

2024-07-15 19:57 UTC, galindocode requested changes

2024-07-15 19:57 UTC, galindocode commented on doc/config-schemas/getRecordingRanges.md
> +| utStart   | string | debe seguir el formato UTC "YYYY-MM-DDTHH:mm:ssZ" ES opcional |
Los formatos de fecha y hora tienen un estandar definido, por favor incluir el link del sition web donde describa el estandar en el que es representado este formato de fecha y hora

2024-07-15 19:57 UTC, galindocode commented on doc/config-schemas/getRecordingSource.md
> +| rtspSource | number | La fuente rtsp del canal |
`rtspSource` debe ser de tipo `string`

2024-07-15 19:57 UTC, galindocode commented on pkg/config/schemas.go
>  	Source string `json:"source"`
Tipo de respuesta no coincide con la de la documentacion

2024-07-16 13:44 UTC, cuervodelviento commented
I believe this methods should be updated as well but wasn't too confident in doing it myself https://github.com/Netsocs-Team/driver.sdk_go/blob/66db7bf290eec6f3ca26f9f016b30418ab4cc000/pkg/event/main.go#L49 @galindocode

2024-07-16 13:53 UTC, merged